# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
#

require_relative '..\vagrant_rancheros_guest_plugin.rb'

$install_rancher_server = <<INSTALL_RANCHER_SERVER
echo Installing Rancher Server
sudo docker run -d --restart=always -p 8080:8080 rancher/server
INSTALL_RANCHER_SERVER

$setup_registry = <<SETUP_REGISTRY
echo adding registry server
sudo echo "172.22.101.106 registry" >> /etc/hosts
SETUP_REGISTRY



Vagrant.configure(2) do |config|

  config.vm.define "rancherserver" do |rancherserver|
  config.vm.guest = :linux
   rancherserver.vm.box= "MatthewHartstonge/RancherOS"
    rancherserver.vm.box_url = "MatthewHartstonge/RancherOS"
    rancherserver.vm.hostname = 'rancherserver'

    rancherserver.vm.network :private_network, ip: "172.22.101.100",
      nic_type: "82545EM"

    rancherserver.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--name", "rancherserver"]
    end

    rancherserver.vm.provision "shell", inline: $setup_registry
    rancherserver.vm.provision "shell", inline: $install_rancher_server
  end
end